//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkzamenSokolov203.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovari
    {
        public string Cod_Tovara { get; set; }
        public string Nazvanie_Tovara { get; set; }
        public string Edenica_Izmereniya { get; set; }
        public decimal Cena { get; set; }
        public float Maks_Skidka { get; set; }
        public int Nomer_Proizvoditel { get; set; }
        public int Nomer_Postavchika { get; set; }
        public int Nomer_Kategorii { get; set; }
        public float Deistvyushaya_Skidka { get; set; }
        public int Kol_vo_Na_Sklade { get; set; }
        public string Opisanie { get; set; }
        public string Izobrajenie { get; set; }
    
        public virtual Kategorii Kategorii { get; set; }
        public virtual Postavchiki Postavchiki { get; set; }
        public virtual Proizvoditeli Proizvoditeli { get; set; }
    }
}
